services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - 8000:8000
    volumes:
      - ./php/src:/backend
  web:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx-container
    ports:
      - 8080:80
    volumes:
      - ./php/src:/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0.34
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - "3001:80"
volumes:
  mysql:
    driver: local
